name: Deploy on staging 
on:
  push: 
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: Ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          mkdir -p /home/runner/.ssh
          cat ~/ssh_key
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          chmod 600 ~/ssh_key

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@54.196.182.129 << 'EOF'
            set -e
            cd deploy-project
            git pull origin main

            export NVM_DIR="$HOME/.nvm"
            if [ ! -d "$NVM_DIR" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            fi
            source "$NVM_DIR/nvm.sh"
            nvm install 22
            nvm use 22

            npm i -g pnpm
            pnpm install
            pnpm run build

            pm2 restart fe
            pm2 restart http-server
            pm2 restart ws-server
          EOF

          
      