name: Deploy on staging 
on:
  push: 
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: Ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls ~/ssh_key
          touch /home/runner/.ssh/know_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key root@54.196.182.129 -t "
          cd deploy-project/ && git pull origin main
          && pnpm install && pnpm run build && pm2 restart fe && pm2 restart http-server
          && pm2 restart ws-server"
          
      